# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseAppInit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseAppInit
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  # pod 'Firebase/AdMob', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'

  target 'FirebaseAppInitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FirebaseAppInit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseAppInit-tvOS

  target 'FirebaseAppInit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
